using CommuteCast.Core;
using System.Buffers.Binary;
using System.Globalization;
using System.Text;

namespace CommuteCast.Infrastructure;

internal static class Mp3Comments
{
    public static string Describe(Job job)
    {
        var settings = job.Settings;
        var model = settings.Engine switch
        {
            "kokoro" => "Kokoro",
            "piper" => "Piper (" + settings.Voice + ")",
            _ => settings.Engine
        };
        var profile = settings.Profile;
        var gaps = job.Chunks.Take(job.Chunks.Count - 1).Count(c => c.Text.TrimEnd().EndsWith('.') || c.Text.EndsWith('\n'));
        var lines = new List<string>
        {
            "Generated by CommuteCast " + typeof(AudioPipeline).Assembly.GetName().Version?.ToString(3),
            "Speech model: " + model,
            "Speech engine: " + settings.Engine,
            "Voice: " + settings.Voice,
            "Pace: " + settings.Speed.ToString(CultureInfo.InvariantCulture) + "x",
            "Provider/model fingerprint: " + (string.IsNullOrEmpty(settings.ProviderFingerprint) ? "not recorded" : settings.ProviderFingerprint),
            "Provider image: " + (settings.ProviderImageId ?? (SpeechProviders.IsHosted(settings.Engine) ? "not applicable (hosted API)" : "not recorded (legacy job)")),
            "Code blocks excluded: " + (settings.ExcludeCode ? "yes" : "no")
        };
        if (settings.Engine == "kokoro")
            lines.Add("Speech language: " + (settings.Voice.StartsWith('b') ? "en-gb" : "en-us"));
        else if (settings.Engine == "piper")
        {
            lines.Add("Speech language: en-US");
            lines.Add("Piper length scale: " + (1 / settings.Speed).ToString(CultureInfo.InvariantCulture));
        }
        if (settings.Speech is { } speech) lines.Add("Requested hosted model: " + speech.Model + "; hosted aliases may change; regenerated speech is not byte-identical.");
        if (job.Episode is { } episode)
        {
            lines.Add("Podcast participants: " + episode.Speakers.Count + "; format: " + episode.Format.Name);
            foreach (var speaker in episode.Speakers.Select((s, i) => (s, i)))
            {
                lines.Add($"Participant {speaker.i + 1}: {speaker.s.Role}; voice: {speaker.s.Voice}; pace: {speaker.s.Speed.ToString(CultureInfo.InvariantCulture)}x");
                if (PodcastScript.LocalDelivery(speaker.s, settings) is { } delivery)
                    lines.Add($"Participant {speaker.i + 1} local voice recipe: " + System.Text.Json.JsonSerializer.Serialize(delivery));
                if (!string.IsNullOrEmpty(speaker.s.Pronunciation))
                    lines.Add($"Participant {speaker.i + 1} pronunciation revision: " + TextPreparation.DictionaryRevision(speaker.s.Pronunciation));
            }
            if (!NaturalChunker.IsNatural(job)) lines.Add("Podcast units normalized to -19 LUFS with -2 dB true-peak target; provider dialogue timing retained inside blocks.");
        }
        if (profile is not null)
        {
            lines.Add("Pronunciation profile: " + profile.Version + "; language: " + profile.Language);
            lines.Add($"Number reading: {profile.Numbers}; acronym reading: {profile.Acronyms}; date reading: {profile.Dates}");
            lines.Add("Dictionary format: " + profile.DictionaryVersion);
        }
        else lines.Add("Pronunciation profile: legacy literal substitutions; numbers, acronyms and dates as written");
        var rules = TextPreparation.ParseDictionary(settings.Pronunciation).Count;
        lines.Add("Custom pronunciation rules: " + rules.ToString(CultureInfo.InvariantCulture));
        if (rules > 0)
            lines.Add("Pronunciation dictionary revision: " + (job.Prepared.ProfileReview?.DictionaryRevision ?? Job.Hash(settings.Pronunciation)));
        lines.Add("Audio: MP3; libmp3lame; 128 kbps; 24000 Hz; mono; one encode from 16-bit PCM");
        if (job.Episode is not null) gaps = job.Chunks.Take(job.Chunks.Count - 1).Count(c => c.Turns![^1].Speaker != job.Chunks[c.Index + 1].Turns![0].Speaker);
        var pause = job.Episode is null ? .15 : .08;
        if (!NaturalChunker.IsNatural(job)) lines.Add(FormattableString.Invariant($"Segments: {job.Chunks.Count}; inserted join pauses: {gaps} at {pause * 1000:0} ms; expected audio duration: {job.Receipts.Sum(r => r.Duration) + gaps * pause:0.000} seconds"));
        if (settings.LocalVoice is { } local)
            lines.Add("Local voice recipe: " + System.Text.Json.JsonSerializer.Serialize(local));
        if (NaturalChunker.IsNatural(job)) lines.Add($"Segments: {job.Chunks.Count}; silence-aware sentence/paragraph joins; measured final loudness target -19 LUFS / -2 dBTP");
        lines.Add(FormattableString.Invariant($"Source characters: {job.Source.Length}; spoken text characters: {job.Prepared.Script.Length}"));
        lines.Add($"Preparation: {job.Prepared.Version}; chunking: {job.ChunkingVersion}; audio contract: {job.AudioContractVersion}");
        lines.Add("Queued UTC: " + job.CreatedUtc.ToUniversalTime().ToString("O", CultureInfo.InvariantCulture));
        lines.Add("Job ID: " + job.Id);
        return string.Join("\r\n", lines);
    }

    public static byte[] CreateFrame(string comment)
    {
        // ID3v2.3 COMM: UTF-16 with BOM, English, empty description, then the text.
        var text = Encoding.Unicode.GetBytes(comment);
        var frame = new byte[checked(22 + text.Length)];
        "COMM"u8.CopyTo(frame);
        BinaryPrimitives.WriteInt32BigEndian(frame.AsSpan(4), frame.Length - 10);
        frame[10] = 1;
        "eng"u8.CopyTo(frame.AsSpan(11));
        frame[14] = 0xff; frame[15] = 0xfe; // empty description BOM and two-byte terminator
        frame[18] = 0xff; frame[19] = 0xfe;
        text.CopyTo(frame, 20); // final two bytes terminate the comment
        return frame;
    }

    public static void WriteFrame(Stream output, byte[] frame)
    {
        // FFmpeg writes comment= as TXXX. Put COMM into reserved ID3 padding on
        // the same exclusive output handle, before its checksum/receipt is saved.
        output.Position = 0;
        Span<byte> header = stackalloc byte[10];
        output.ReadExactly(header);
        if (!header[..3].SequenceEqual("ID3"u8) || header[3] != 3 || header[4] != 0 || header[5] != 0 ||
            header[6..].ContainsAnyInRange((byte)128, byte.MaxValue))
            throw new IOException("The encoder produced an unsupported MP3 metadata header.");
        var size = (header[6] << 21) | (header[7] << 14) | (header[8] << 7) | header[9];
        if (size > 128 * 1024 || size > output.Length - 10)
            throw new IOException("The encoder produced an invalid MP3 metadata size.");
        var tag = new byte[size];
        output.ReadExactly(tag);
        var offset = 0;
        while (offset + 10 <= tag.Length && tag[offset] != 0)
        {
            var length = BinaryPrimitives.ReadInt32BigEndian(tag.AsSpan(offset + 4));
            if (length <= 0 || length > tag.Length - offset - 10)
                throw new IOException("The encoder produced an invalid MP3 metadata frame.");
            offset += 10 + length;
        }
        if (tag.Length - offset < frame.Length || tag.AsSpan(offset).ContainsAnyExcept((byte)0))
            throw new IOException("The encoder did not reserve enough MP3 comment space.");
        output.Position = 10 + offset;
        output.Write(frame);
    }
}
